name: CI

on:
  push:
    branches:
      - 'dpm'

  pull_request:
    branches:
      - 'dpm'

jobs:
  androidBuild:
    defaults:
      run:
        working-directory: ./src/android

    name: Android build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install build dependencies
        run: python -m pip install --upgrade pip lxml scons

      - name: Assemble app debug APK
        run: ./gradlew assembleDebug --stacktrace --debug 

      - name: Upload app APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: src/android/RHVoice-core/build/outputs/apk/debug/RHVoice-core-debug.apk

